In [4]:
############# DATA CLEANING
## STRING METHODS

mystring= "Once upon a midnight when i pondered \n Hi these is jinesh"
## SPLIT METHOD puts each element of a string into a list. We can pass a tring argument and it will split the string where the it appears.
a =mystring.split('i')   
print(a) 
mystringtemp="1 2 3 4 5 6 7 8 9"
b = mystringtemp.split('5')
print(b)

## JOIN() METHOD concats any number of strings with a given pattern
dateList = ['01', '01', '2023']
print('/'.join(dateList))

## STRIP() METHOD removes spaces at the beginning and end of a string
string2 = '  s ads     '
print(string2.strip())

##  startswith(string) returns True or False
'Name of user is Lucas'.startswith('Name')

## returning a Tuple of booleans
'ea' in 'team', 'f' in 'team'

## SLICE(start, finish, step)
c = 'hello'
slice_obj = slice(2)
c[slice_obj] ## output = 'he'

['Once upon a m', 'dn', 'ght when ', ' pondered \n H', ' these ', 's j', 'nesh']
['1 2 3 4 ', ' 6 7 8 9']
01/01/2023
s ads


'he'

In [13]:
## STRING METHODs practice
list_of_Account=['Acc1.ID242342 : London . 06/03/2019',
                 'Acc1.ID2423342 : London . 07/03/2019',
                 'banana',
                 'Acc1.ID24243342 : London . 08/03/2019',
                 'Acc1.ID23442342 : London . 09/03/2019',
                 'Acc1.ID24233442 : London . 10/03/2019']


## we first separate the string into list items whenever a "." shows, then extract the last element of the list
dates = [string.split('.')[-1].strip() for string in list_of_Account if string.startswith('Acc')]
print(dates)

## geting the acounts IDs
account_id = [string.split('ID')[1].split(':')[0].strip() for string in list_of_Account if string.startswith('Acc') == True]
print(account_id)

## getting location
account_location = [string.split(':')[1].split('.')[0].strip() for string in list_of_Account if string.startswith('Acc') == True]
print(account_location)

['06/03/2019', '07/03/2019', '08/03/2019', '09/03/2019', '10/03/2019']
['242342', '2423342', '24243342', '23442342', '24233442']
['London', 'London', 'London', 'London', 'London']


In [ ]:
## NUMPY INTRO
def makeMatrix(n_rows, n_columns):
    return [list(range(i*n_columns, n_columns*(i + 1))) for i in range(n_rows)]

test_data = makeMatrix(40, 5)

In [30]:
%%timeit ## testing execution time with list
sum([sum(r) for r in test_data])

6.25 µs ± 198 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
pip install numpy ## installing numpy

In [ ]:
import numpy as np ## IMPORTING NUMPY PACKAGE
test_array = np.array(test_data) ## USING ARRAY() METHOD TO CREATE AN ARRAY

In [25]:
%%timeit ## timing execution time with array
test_array.sum() ## summing elemtns of a array takes way shorter that doing it with lists. Arrays are more efficent to work with numbers

2.34 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [53]:
## NDARRAY -> multidimensional array introduced in NumPy (numerical Python) -> all elements of this type of data structure are of the same type.
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
## print(arr2d)
## print(arr[3])   # array scaler gettig one element from numpy array
print(arr2d[0][2]) ## accessing multid arrays
print(arr2d[0,2]) ## same as line above

print(arr.shape)    # get the size of row
print(arr2d.shape)   # get the size of row and columns
print(arr.dtype)   # get the data type

# these is for mutiplying 2 with the array elements
arr_squared = arr *2
print(arr_squared)
# these code is for calculating array sum
arr_Sum=np.sum(arr)
print(arr_Sum)

# these code is for doing numpy transpose of matrix
arr2d_transpose=np.transpose(arr2d)
print(arr2d_transpose)

## COMPLEX NUMBERS
acomplex=np.array([1,2,3],dtype="complex")
print(acomplex)

[1 2 3 4 5]
3
3
(5,)
(3, 3)
int32
[ 2  4  6  8 10]
15
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1.+0.j 2.+0.j 3.+0.j]


In [42]:
## GENERATING RANGES
array = np.linspace(0, 20, 5, dtype=int) ## end point included
print(array)

array2 = np.arange(0, 11, 2) ##  end point not included
print(array2)

[ 0  5 10 15 20]
[ 0  2  4  6  8 10]


In [51]:
## RANDOM VALUES
np.random.seed(0) ## set random set for consistency
array_random = np.random.rand(5, 3) # generates a random matrix of 5 rows and 3 col
print(array_random)

[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]
 [0.76590786 0.51841799 0.2968005 ]
 [0.18772123 0.08074127 0.7384403 ]
 [0.44130922 0.15830987 0.87993703]]


In [52]:
array_zeros = np.zeros((2,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [80]:
## PRACTICE
array = np.array([1, 2, 3, 4], ndmin=2) ## ndmin sets the dimensions of the array
print(array)

print(array.ndim) ## returns dimension of an array

##ACCESSING elements
array = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
array[1, 0] ## output = 50 (index stars at zero)
array[-1] ## output row 2
array[-1, 0] ## output 50
array[0, -1] ## output 40
array.shape ## SHAPE() returns dimentions nxm of the arrayy
array = array.reshape(4, 2) ## reshape() changes an array to the specified dimensions
array[1:] ## returns matrix but excludes first row.
array[:1] ## returns first row
array[1:, 2:]


[[1 2 3 4]]
2


array([], shape=(3, 0), dtype=int32)

In [102]:
## subsetting 
np.random.seed(17)
small_array=np.random.rand(12)
## print(small_array.shape) ## SHAPE() returns dimentions nxm of the arrayy

small_array = small_array.reshape(4,3)
## print(small_array[2:]) ## first index 2 indicates the rows to remove
## small_array[:1] = 0 ## set first row to zeros
small_array = small_array.reshape(4,3)
## small_array[:, 2:] = 0 ## sets last column to zeros
##small_array[1:, 2] = 0 ## rows> from index 1 until end / column > index 2 (last column)
small_array[2, :2] = 0 ## rows> only 3erd row (index 2), coolumns > from 0 to 1 (index 2 not included)
print(small_array)


[[0.294665   0.53058676 0.19152079]
 [0.06790036 0.78698546 0.65633352]
 [0.         0.         0.03906292]
 [0.3578136  0.94568319 0.06004468]]


In [117]:
## MAKING A COPY
shallow_copy_array = small_array.view() ## makes a SHALLOW copy
small_array_copy = small_array.copy() ## makes a DEEP copy of the array.
print(small_array_copy)

[[0.294665   0.53058676 0.19152079]
 [0.06790036 0.78698546 0.65633352]
 [0.         0.         0.03906292]
 [0.3578136  0.94568319 0.06004468]]


In [130]:
## CONDITIONAL INDEXING
small_array_copy[:] > 0.5

small_array_copy[:, 1] > 0.5

small_array_copy[2, :] > 0.5

small_array_copy[2:4, 1:] > 0.5

small_array_copy[small_array_copy[:, 1] > 0.5, :] ## pass booleans array for all colums. only TRUE rows will be returned


array([[0.294665  , 0.53058676, 0.19152079],
       [0.06790036, 0.78698546, 0.65633352],
       [0.3578136 , 0.94568319, 0.06004468]])

In [ ]:
## MATRIX OPERATIONS
np.random.seed(17)
array1= np.random.rand(10,2)
array2= np.random.rand(10,2)
array3= array1+array2
array3= array1-array2
array3= array1*array2 ## multiplies each element of the same index
array3 = np.dot(array1, array2.T) ## this is a proper matrix multiplication. we transpose array2


array3

In [ ]:
array1.std()
array1.max()
array1.argmax() ## returns the max argument passed
array1.min(); np.min(array1) ## different ways, same result
print(array1.mean()); print(np.mean(array1))
np.nanmean(array1) ## works without nan numbers. for almost all methods there is nan method


In [ ]:
## SAVING NUMPY VARIABLES. np.save(name_you_give_to_file, variable)
np.save('array.npy', array1)
np.save('2darray.npy' , arr2d)

## loading the data saved
get_array = np.load('array.npy') ## I can now perfom operations on this variable

get_array2 = np.load('2darray.npy')
## get_array2*2 ## performing an operation on new variable from loaded data

np.savetxt('sampletext.csv', test_data, delimiter=',') ## saves an array to a text file
retrievefromcsv = np.loadtxt('sampletext.csv', delimiter=',')
np.savetxt('samplearray.csv', array3, delimiter=',')
text_array = np.loadtxt('samplearray.csv', delimiter=',')
## text_array
type(get_array[0, 0])
%ls -l *.npy ## checking which .npy files are in current folder



In [211]:
import numpy as np
## WE CAN CREATE CUSTOM OBJECTS. WE CREATE AN NP ARRAY BY INSERTING EACH LINE AS TUPLE
a = np.array([('abc',21,50),("jinesh",67,8)], dtype=object) ## with dtype=object I can store different datatypes.
a = np.array([('abc',21,50),("jinesh",67,8)]) ## without dtype all gets converted to string automatically
print(a)

[['abc' '21' '50']
 ['jinesh' '67' '8']]


In [232]:
import numpy as np
class Myclass:
    def __init__(self,value1,valye2):
        self.value=value1
        self.value2=valye2
    
obj= Myclass(42,'asdhkasd')
np.save('abc.npy',obj)
loaded_obj=np.load('abc.npy',allow_pickle=True)
loaded_obj_type=loaded_obj.item()
## print(loaded_obj_type.value)

## SAVING AND LOADING MULTIPLE OBJECTS
obj1 = Myclass(50, 'Lucas')
obj2 = Myclass(51, 'Vit')
np.savez('multiple_objs.npz', obj1=obj1, obj2=obj2) ## SAVING using savez(). Extension is npz
load_objs = np.load('multiple_objs.npz', allow_pickle=True) ## loading into a new variable
loaded_obj_1 = load_objs['obj1'].item() # creating a variable with object 1
loaded_obj_1.value ## retrieving value inside the object
loaded_obj_1.value2 ## retrieving value inside the object

'Lucas'

In [1]:
!pip3 install pandas

In [2]:
## PANDAS. uses numpy as base object. ideal to work with tables and dataframes.
import pandas as pd
import numpy as np

## creating a series (column)
s1 = pd.Series(['a', 'b', 'c'])
## creating custom indexes with the 'index' argument
s2 = pd.Series(s1, index= [1, 2, 3])
print(s2.index)

## creating a dataframe
df1 = pd.DataFrame({'Customers': ['A', 'B', 'C', 'D'], 'Balance': [45661, 43585, 6214, 89862], 'Age': [45, 66, 29, np.NaN]})

## visualizing columns and its information
## print(df1['Customers']); print(df1['Balance'])




Int64Index([1, 2, 3], dtype='int64')


In [ ]:
## OPENING A FILE AND ANALYZING THE DATA
df = pd.read_csv('college_scorecard_2017-18.zip', dtype={'OPEID': str}) ## setting the dtype in the OPEID column to be a string so the leaeding zeros don't get eraised. Int erraises leading zeros

In [40]:
df.head(10) ## display first rows. I can pass the number of rows to return
# df.tail() ## last 5 rows

OPEID                               INSTNM            CITY STABBR  \
0  00100200             Alabama A & M University          Normal     AL   
1  00105200  University of Alabama at Birmingham      Birmingham     AL   
2  02503400                   Amridge University      Montgomery     AL   
3  00105500  University of Alabama in Huntsville      Huntsville     AL   
4  00100500             Alabama State University      Montgomery     AL   
5  00105100            The University of Alabama      Tuscaloosa     AL   
6  00100700    Central Alabama Community College  Alexander City     AL   
7  00100800              Athens State University          Athens     AL   
8  00831000      Auburn University at Montgomery      Montgomery     AL   
9  00100900                    Auburn University          Auburn     AL   

          ZIP                    INSTURL  REGION  LOCALE  ADM_RATE  COSTT4_A  
0       35762              www.aamu.edu/       5    12.0    0.9027   22886.0  
1  35294-0110                www.uab.edu       5    12.0    0.9181   24129.0  
2  36117-3553  www.amridgeuniversity.edu       5    12.0       NaN   15080.0  
3       35899                www.uah.edu       5    12.0    0.8123   22108.0  
4  36104-0271              www.alasu.edu       5    12.0    0.9787   19413.0  
5  35487-0166                www.ua.edu/       5    12.0    0.5330   28836.0  
6       35010               www.cacc.edu       5    32.0       NaN   10045.0  
7       35611             www.athens.edu       5    31.0       NaN       NaN  
8  36117-3596                www.aum.edu       5    12.0    0.8254   19892.0  
9       36849             www.auburn.edu       5    13.0    0.8393   30458.0

In [38]:
df.info() ## getting general overview info about the df
# by default, strings are pushed as datatype 'object'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7058 entries, 0 to 7057
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   OPEID     7058 non-null   object 
 1   INSTNM    7058 non-null   object 
 2   CITY      7058 non-null   object 
 3   STABBR    7058 non-null   object 
 4   ZIP       7058 non-null   object 
 5   INSTURL   7039 non-null   object 
 6   REGION    7058 non-null   int64  
 7   LOCALE    6614 non-null   float64
 8   ADM_RATE  2019 non-null   float64
 9   COSTT4_A  3572 non-null   float64
dtypes: float64(3), int64(1), object(6)
memory usage: 551.5+ KB


In [26]:
df.shape ## viewing dimensions of the table.

(7058, 10)

In [41]:
df.index ## shows info about the index

RangeIndex(start=0, stop=7058, step=1)

In [42]:
df.columns ## show all columns

Index(['OPEID', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'INSTURL', 'REGION',
       'LOCALE', 'ADM_RATE', 'COSTT4_A'],
      dtype='object')

In [32]:
pd.options.display.max_rows = 61 ## changing max rows that can display
print(pd.options.display.max_rows) ## max rows that will be displayed

61


In [43]:
## renaming a column name
df.rename(columns={'STABBR': 'STATE'})

OPEID                                             INSTNM  \
0     00100200                           Alabama A & M University   
1     00105200                University of Alabama at Birmingham   
2     02503400                                 Amridge University   
3     00105500                University of Alabama in Huntsville   
4     00100500                           Alabama State University   
...        ...                                                ...   
7053  00108163                   Arizona State University at Yuma   
7054  04223701  Bay Area Medical Academy - San Jose Satellite ...   
7055  04228101                        High Desert Medical College   
7056  04221501                                       BCI - Malden   
7057  04182601          Health Career Institute- Lauderdale Lakes   

                  CITY STATE         ZIP                    INSTURL  REGION  \
0               Normal    AL       35762              www.aamu.edu/       5   
1           Birmingham    AL  35294-0110                www.uab.edu       5   
2           Montgomery    AL  36117-3553  www.amridgeuniversity.edu       5   
3           Huntsville    AL       35899                www.uah.edu       5   
4           Montgomery    AL  36104-0271              www.alasu.edu       5   
...                ...   ...         ...                        ...     ...   
7053              Yuma    AZ   853656900               www.asu.edu/       6   
7054          San Jose    CA       95113            www.bamasf.com/       8   
7055         Lancaster    CA   935340000               www.hdmc.edu       8   
7056            Malden    MA    21480000           bostoncareer.org       1   
7057  Lauderdale Lakes    FL   333137268               www.hci.edu/       5   

      LOCALE  ADM_RATE  COSTT4_A  
0       12.0    0.9027   22886.0  
1       12.0    0.9181   24129.0  
2       12.0       NaN   15080.0  
3       12.0    0.8123   22108.0  
4       12.0    0.9787   19413.0  
...      ...       ...       ...  
7053     NaN       NaN       NaN  
7054     NaN       NaN       NaN  
7055     NaN       NaN       NaN  
7056     NaN       NaN       NaN  
7057     NaN       NaN       NaN  

[7058 rows x 10 columns]

In [ ]:
## OPENING AN EXCEL FILE


In [ ]:
## GETTING DATA FROM WEB. first we need xlml package
!pip install lxml

In [21]:
url = 'https://en.wikipedia.org/w/index.php?title=World_population&oldid=948301297'
df_web = pd.read_html(url)
# print the object to explore it. we see that index 12 is where the world population table is
## print(df_web)
df_web[12].head()

Year  World           Asia         Africa       Europe  \
0  2000   6144  3,741 (60.9%)    811 (13.2%)  726 (11.8%)   
1  2005   6542  3,978 (60.8%)    916 (14.0%)  729 (11.2%)   
2  2010   6957  4,210 (60.5%)  1,039 (14.9%)  736 (10.6%)   
3  2015   7380  4,434 (60.1%)  1,182 (16.0%)  743 (10.1%)   
4  2020   7795  4,641 (59.5%)  1,341 (17.2%)   748 (9.6%)   

  Latin America/Caribbean Northern America    Oceania  
0              522 (8.5%)       312 (5.1%)  31 (0.5%)  
1              558 (8.5%)       327 (5.0%)  34 (0.5%)  
2              591 (8.5%)       343 (4.9%)  37 (0.5%)  
3              624 (8.5%)       357 (4.8%)  40 (0.5%)  
4              654 (8.4%)       369 (4.7%)  43 (0.6%)

In [46]:
################################ LAMBDA function. It's a runtime function. Also called anonymous function
increment_by_one = (
    lambda x: x + 1
)  ## creating a lambda function to increment a number by 1
increment_by_one(5)  ## calling the instance of the function and passing an argument

multiply_nums = lambda x, y, z=1: x * y * z
multiply_nums(5, 5, 5)

check_number = lambda x: x if (x > 10) else "not greater than 10"
check_number(10)
print(
    (lambda x: x if (x > 10) else "not greater than 10")(10) ## I can also call the func directly
)  

############################################## USING LAMBDA WITH MULTIPLE PARAMENTERS
suma = lambda *args: sum(args)
suma(1, 2, 3, 4)

multiplied = lambda x, *args, **kargs: x * sum(args) * kargs['multiplier']
multiplied(1, 2, 3, 4, multiplier = 2) ## 1 * (2+3+4) * 2 = 18

########################################## USING LAMBDA WITH FOR LOOP
aList = list(range(20))
bList = []
for i in aList:
    bList.append((lambda i: i**2)(i))

# print(bList)

############################################################## USING LAMBDA WITH FILTER() and MAP() methods.
list(
    filter(lambda x: x > 10, aList) ## filter() method takes a function and an iterable. We can pass a lambda function
)  
tuple(
    filter(lambda x: x > 10, aList) ## filter() method takes a function and an iterable. We can pass a lambda function
)  

list(map(lambda x: {x: "even"} if (x % 2 == 0) else x, aList)) ## map() method


not greater than 10


[{0: 'even'},
 1,
 {2: 'even'},
 3,
 {4: 'even'},
 5,
 {6: 'even'},
 7,
 {8: 'even'},
 9,
 {10: 'even'},
 11,
 {12: 'even'},
 13,
 {14: 'even'},
 15,
 {16: 'even'},
 17,
 {18: 'even'},
 19]

In [62]:
## USING map() and apply() with Dataframes
import pandas as pd
df = pd.DataFrame({'id':[1,2,3,4,5],'name':['Lucas','Pedro','Juan','Matias','Miguel']})

#################################
# creating a new column from an existing one using lambda and map()
df['fullName'] = df['name'].map(lambda x: f"he's {x}")
display(df) ## display() is better for printing df in pandas than using print()


id    name     fullName
0   1   Lucas   he's Lucas
1   2   Pedro   he's Pedro
2   3    Juan    he's Juan
3   4  Matias  he's Matias
4   5  Miguel  he's Miguel

In [61]:
## USING APPLY() METHOD
## apply() method works with vectorized variables or series(columns)
df['balance'] = df['id'].apply(lambda x: 1000 if(x in [1, 2]) else 0) # here we assigned a balance of 1000 to ids 1 and 2
display(df)

## https://stackoverflow.com/questions/19798153/difference-between-map-applymap-and-apply-methods-in-pandas

id    name     fullName  balance
0   1   Lucas   he's Lucas     1000
1   2   Pedro   he's Pedro     1000
2   3    Juan    he's Juan        0
3   4  Matias  he's Matias        0
4   5  Miguel  he's Miguel        0

In [91]:
## USING REDUCE() METHOD
from functools import reduce
result = reduce(lambda x, y: x + y, aList)
result

18

In [1]:
################## DATA CLEANING #########################
# LOADING DATA
import pandas as pd
test_df = pd.read_csv('college_scorecard_2017-18.zip', dtype= {'OPEID': str})

In [ ]:
## READING DATA INFO
test_df.info()

In [161]:
## READING SHAPE
test_df.shape

(7058, 10)

In [180]:
## full description of the data
test_df.describe(include='all')

OPEID         INSTNM      CITY STABBR    ZIP  \
count       1822           1822      1822   1822   1822   
unique      1817           1806      1030     55   1772   
top     00370200  Union College  New York     NY  02215   
freq           2              3        30    181      3   
mean         NaN            NaN       NaN    NaN    NaN   
std          NaN            NaN       NaN    NaN    NaN   
min          NaN            NaN       NaN    NaN    NaN   
25%          NaN            NaN       NaN    NaN    NaN   
50%          NaN            NaN       NaN    NaN    NaN   
75%          NaN            NaN       NaN    NaN    NaN   
max          NaN            NaN       NaN    NaN    NaN   

                      INSTURL       REGION       LOCALE     ADM_RATE  \
count                    1822  1822.000000  1822.000000  1822.000000   
unique                   1764          NaN          NaN          NaN   
top     https://www.devry.edu          NaN          NaN          NaN   
freq                       16          NaN          NaN          NaN   
mean                      NaN     4.055434    19.840834     0.684968   
std                       NaN     2.129189     9.461905     0.215220   
min                       NaN     0.000000    -3.000000     0.000000   
25%                       NaN     2.000000    12.000000     0.547050   
50%                       NaN     4.000000    21.000000     0.701700   
75%                       NaN     5.000000    31.000000     0.832050   
max                       NaN     9.000000    43.000000     1.000000   

            COSTT4_A  
count    1822.000000  
unique           NaN  
top              NaN  
freq             NaN  
mean    34914.804061  
std     15242.893066  
min         0.000000  
25%     22204.250000  
50%     32065.000000  
75%     45740.000000  
max     72717.000000

In [69]:
## DROPPING ROWS WITH NA VALUES IN SPECIFIC COLUMNS
test_df.dropna(subset=['COSTT4_A', 'ADM_RATE'], inplace=True)

## REPLACING NA with a 'NOT GIVEN'
test_df.fillna(0, inplace=True)

## REPLACING VALUES
## replaces rates greater than 0.9 with 1.
test_df['ADM_RATE'] = test_df['ADM_RATE'].apply(lambda x: x if(x<=0.9) else 1)

## cleaning zip codes from special characters
test_df['ZIP'].replace('-', '', inplace=True, regex=True)

## REMOVING DUPLICATES
test_df.drop_duplicates(inplace=True, keep='first') ## fisrt specifies that I want to keep one record as original and drop the rest of duplicates

## CHANGING COLUMN NAME
test_df.rename(columns={'STABBR': 'STATE'}, inplace=True)

(1822, 10)

In [3]:
## corr() method returns a table with correlation between columns.
test_df.corr() 

C:\Users\Lucas\AppData\Local\Temp\ipykernel_13640\3536928793.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  test_df.corr()


REGION    LOCALE  ADM_RATE  COSTT4_A
REGION    1.000000 -0.062665 -0.011816 -0.177156
LOCALE   -0.062665  1.000000  0.028920 -0.064817
ADM_RATE -0.011816  0.028920  1.000000 -0.301401
COSTT4_A -0.177156 -0.064817 -0.301401  1.000000

In [7]:
## BECAUSE IM WORKING WITH HA DATAAFRAME I NEED DOUBLE BRACKETS TO ACCESS THE METHOD
test_df[['REGION', 'LOCALE']].head()

REGION  LOCALE
0       5    12.0
1       5    12.0
3       5    12.0
4       5    12.0
5       5    12.0

In [8]:
## nunique() returns the unique number of appearances in a column
test_df['CITY'].nunique() 

1030

In [20]:
## loc[] method allows label based indexing. It can access values in specified rows using bracket notation.
test_df.loc[3, 'INSTNM']
test_df.loc[:3, 'INSTNM':'ZIP'] ## I can access a range of rows in a column range
test_df.loc[[3, 10], ['INSTNM', 'ZIP']] ## Accessing only a few rows of certain columns.

## iloc[] method allows pure numerical indexing.
test_df.iloc[:3] ## rows 0 to 3 for all columns
test_df.iloc[:3, 3:6] ## rows 0 to 3 and colums with index 3 to 6
test_df.iloc[:3, [0, 1, 5, 9]] ## rows from 0 to 3, and columns with index 0, 1, 5 and 9

OPEID                               INSTNM        INSTURL  COSTT4_A
0  00100200             Alabama A & M University  www.aamu.edu/   22886.0
1  00105200  University of Alabama at Birmingham    www.uab.edu   24129.0
3  00105500  University of Alabama in Huntsville    www.uah.edu   22108.0

In [43]:
## isin() useful method for filtering
alabama_inst = test_df[test_df['STATE'].isin(['AL'])]
alabama_inst.head()

## query() also handy for filtering
test_df.query('ADM_RATE > 0.8')
test_df.query('CITY == "Boston" and ADM_RATE > 0.85')

## filtering with brackets
test_df[(test_df['CITY'] == 'Boston') & (test_df['ADM_RATE'] > 0.85)]

OPEID                               INSTNM        CITY STATE        ZIP  \
0  00100200             Alabama A & M University      Normal    AL      35762   
1  00105200  University of Alabama at Birmingham  Birmingham    AL  352940110   
3  00105500  University of Alabama in Huntsville  Huntsville    AL      35899   
4  00100500             Alabama State University  Montgomery    AL  361040271   
5  00105100            The University of Alabama  Tuscaloosa    AL  354870166   

         INSTURL  REGION  LOCALE  ADM_RATE  COSTT4_A  
0  www.aamu.edu/       5    12.0    1.0000   22886.0  
1    www.uab.edu       5    12.0    1.0000   24129.0  
3    www.uah.edu       5    12.0    0.8123   22108.0  
4  www.alasu.edu       5    12.0    1.0000   19413.0  
5    www.ua.edu/       5    12.0    0.5330   28836.0

In [47]:
## setting new indexes.
df_city=test_df.set_index('CITY') ## column CITY will now be index.
df_city.head() ## we see that CITY column is now the first one as it's now the index
df_city.loc['Cambridge'] ## getting all rows with cambridge index

## Setting two column indexxes and accessing data with loc[]
test_df.set_index(['CITY', 'STATE']).loc[('Bloomington', 'MN')] 

C:\Users\Lucas\AppData\Local\Temp\ipykernel_13640\3120545834.py:6: PerformanceWarning: indexing past lexsort depth may impact performance.
  test_df.set_index(['CITY', 'STATE']).loc[('Bloomington', 'MN')]


OPEID                     INSTNM        ZIP  \
CITY        STATE                                                   
Bloomington MN     04227800  Bethany Global University  554382849   

                                      INSTURL  REGION  LOCALE  ADM_RATE  \
CITY        STATE                                                         
Bloomington MN     https://www.bethanygu.edu/       4    13.0       1.0   

                   COSTT4_A  
CITY        STATE            
Bloomington MN      22570.0

In [67]:
## droping columns using axis parameter
df_new = test_df
## df_new = test_df.drop(0, axis) ## axis=1 or axis='columns' drops a column // axis=0 or axis='index' drops rows
df_new = test_df.drop('CITY', axis=1) ## axis=1 or axis='columns' drops a column // axis=0 or axis='index' drops rows
df_new.columns

Index(['OPEID', 'INSTNM', 'STATE', 'ZIP', 'INSTURL', 'REGION', 'LOCALE',
       'ADM_RATE', 'COSTT4_A'],
      dtype='object')

In [70]:
## count non-NA values for each column
test_df.count()

OPEID       1822
INSTNM      1822
CITY        1822
STATE       1822
ZIP         1822
INSTURL     1822
REGION      1822
LOCALE      1822
ADM_RATE    1822
COSTT4_A    1822
dtype: int64

In [ ]:
import pandas as pd
df_econ = pd.read_excel("AGI_zipcode_2016.xlsx",dtype={'zipcode':str})
df_econ.head()
df_merged=df.merge(df_econ,left_on='ZIP',right_on='zipcode', how='left')
df_merged[['INSTNM','ZIP','AGI']].head(10)

In [82]:
!pip install openpyxl ## to read excel files

     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ----------------- -------------------- 112.6/250.0 kB 3.3 MB/s eta 0:00:01
     -------------------------------------- 250.0/250.0 kB 3.1 MB/s eta 0:00:00


In [7]:
import pandas as pd
zipcode_df = pd.read_excel('AGI_zipcode_2016.xlsx', dtype={'zipcode': str})
inst_df = pd.read_csv('college_scorecard_2017-18.zip', dtype={'OPEID': str})

In [8]:
## JOINING TABLES merge() method
## LEFT JOIN
inst_zipcode = inst_df.merge(zipcode_df, left_on='ZIP', right_on='zipcode', how='left')

In [12]:
inst_zipcode.head()
inst_zipcode[['INSTNM','ZIP','zipcode']].head(10)

INSTNM         ZIP zipcode
0             Alabama A & M University       35762     NaN
1  University of Alabama at Birmingham  35294-0110     NaN
2                   Amridge University  36117-3553     NaN
3  University of Alabama in Huntsville       35899     NaN
4             Alabama State University  36104-0271     NaN
5            The University of Alabama  35487-0166     NaN
6    Central Alabama Community College       35010   35010
7              Athens State University       35611   35611
8      Auburn University at Montgomery  36117-3596     NaN
9                    Auburn University       36849     NaN

In [36]:
## sorting values in descending order
inst_df.sort_values('ADM_RATE', ascending=False).head(20)
inst_df['ADM_RATE'].mean()
inst_df['REGION'].value_counts()

In [30]:
inst_df.dropna(subset=['ADM_RATE'], inplace=True)
inst_df.count()

OPEID       2019
INSTNM      2019
CITY        2019
STABBR      2019
ZIP         2019
INSTURL     2017
REGION      2019
LOCALE      2019
ADM_RATE    2019
COSTT4_A    1822
dtype: int64

In [54]:
inst_df[["STABBR","REGION"]].groupby("REGION")["STABBR"].unique()

REGION
0                                        [CO, MD, NY]
1                            [CT, ME, MA, NH, RI, VT]
2                            [NY, DE, DC, MD, NJ, PA]
3                                [IL, IN, MI, OH, WI]
4                        [IA, KS, MO, MN, NE, ND, SD]
5    [AL, AR, FL, GA, KY, LA, MS, NC, SC, TN, VA, WV]
6                                    [AZ, NM, OK, TX]
7                                [CO, ID, MT, UT, WY]
8                            [AK, CA, HI, NV, OR, WA]
9                                    [PR, FM, VI, GU]
Name: STABBR, dtype: object